dbt_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /Users/zachshirah/code/projects/golf-pool-app/dbt_project/data/golf.duckdb
    prod:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH') }}"